### ISSUE TITLE
cannot load model

### ISSUE THREAD

**Issue by mathpopo** [myyhlee/easy-to-use-CleanUNet#1]
fisrt thank you , i use pyton3.8  torch 1.12

(CleanUNet3.8) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/easy-to-use-CleanUNet$ python denoise_simple.py -c configs/DNS-large-high.json --ckpt_pat ./exp/DNS-large-high/checkpoint/pretrained.pkl ./test.mp4
exp_path: DNS-large-high
CleanUNet Parameters: 46.071937M;  
Traceback (most recent call last):
  File "denoise_simple.py", line 153, in <module>
    denoise(files, args.ckpt_path, sr, batch_size=bs)
  File "denoise_simple.py", line 85, in denoise
    checkpoint = torch.load(ckpt_path, map_location='cpu')
  File "/home/chenxin/disk1/anaconda3/envs/CleanUNet3.8/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/chenxin/disk1/anaconda3/envs/CleanUNet3.8/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

i guess the version is not right?

**Comment by mathpopo** [comment]
(CleanUNet3.8) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/easy-to-use-CleanUNet$ pip show torch
Name: torch
Version: 1.12.0+cu116
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/chenxin/disk1/anaconda3/envs/CleanUNet3.8/lib/python3.8/site-packages
Requires: typing-extensions
Required-by: cleanunet, torchaudio, torchvision

**Comment by mathpopo** [comment]
(pytorch-2.1.0) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/easy-to-use-CleanUNet$ pip show torch
Name: torch
Version: 2.1.0+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/chenxin/disk1/anaconda3/envs/pytorch-2.1.0/lib/python3.11/site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, triton, typing-extensions
Required-by: torchaudio, torchvision
also same issue

**Comment by mathpopo** [comment]
(pytorch-2.1.0) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/easy-to-use-CleanUNet$  python denoise_simple.py -c configs/DNS-large-high.json --ckpt_pat ./exp/DNS-large-high/checkpoint/pretrained.pkl ./test.mp4
exp_path: DNS-large-high
CleanUNet Parameters: 46.071937M;  
Traceback (most recent call last):
  File "/home/chenxin/disk1/github/easy-to-use-CleanUNet/denoise_simple.py", line 153, in <module>
    denoise(files, args.ckpt_path, sr, batch_size=bs)
  File "/home/chenxin/disk1/github/easy-to-use-CleanUNet/denoise_simple.py", line 85, in denoise
    checkpoint = torch.load(ckpt_path, map_location='cpu')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chenxin/disk1/anaconda3/envs/pytorch-2.1.0/lib/python3.11/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chenxin/disk1/anaconda3/envs/pytorch-2.1.0/lib/python3.11/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by mathpopo** [comment]
https://github.com/thu-coai/CDial-GPT/issues/94

**Comment by mathpopo** [comment]
wget https://github.com/NVIDIA/CleanUNet/raw/2f930ce6660e76b6265c07da4027b414adb24ab1/exp/DNS-large-full/checkpoint/pretrained.pkl
